version: '3.1'
services:
  staff:
    network_mode: bridge
    container_name: staff
    image: andrewdarialov/staffcontroller:latest
    build: ./
    ports:
      - "8889:8889"
    environment:
      - POSTGRES_PASSWORD=1415926
      - POSTGRES_USER=postgres
      - POSTGRES_DB=staff
      - DB_SERVER=postgresqldb-staff
    links:
      - postgresqldb-staff

  postgresqldb-staff:
    network_mode: bridge
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=1415926
      - POSTGRES_USER=postgres
      - POSTGRES_DB=staff
    volumes:
      - postgres-data-staff:D:\volumes\staffservice
volumes:
  postgres-data-staff:
