apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: staff
  name: staff
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: staff
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.service: staff
    spec:
      containers:
      - env:
        - name: DB_SERVER
          value: postgresqldb-staff
        - name: POSTGRES_DB
          value: staff
        - name: POSTGRES_PASSWORD
          value: "1415926"
        - name: POSTGRES_USER
          value: postgres
        image: andrewdarialov/staffcontroller:latest
        imagePullPolicy: ""
        name: staff
        ports:
        - containerPort: 8889
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
